import Head from 'next/head';
import { useState } from 'react';

import { withPageAuthRequired } from '@auth0/nextjs-auth0';
import Product from '../components/Product';
import ImageTopper from '../components/ImageTopper';
import Banner from '../components/Banner'
import Navbar from '../components/navbar';
import Stripe from 'stripe'
import { loadStripe } from '@stripe/stripe-js'


export default function Home() {
  return (
    <>
      <Head>
        <title>eCanteen | Catalogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Navbar />
      <ImageTopper 
      heading="Catalogue"
      imagelarge="https://i.ibb.co/HxXSY0j/jason-wang-Nx-Awry-Abt-Iw-unsplash-1-1.png"
      imagesmall="https://i.ibb.co/B6qwqPT/jason-wang-Nx-Awry-Abt-Iw-unsplash-1.png"
      />
      <div className="mt-10 grid lg:grid-cols-2 gap-x-8 gap-y-8 items-center">
        <ul>
          {prices.map((price) => 
            <li key={price.id}>
              <Product
              productname={price.product.name}
              productprice={((price.unit_amount) / 100).toFixed(2)}
              productimage={price.product.images[0]}
              />
            </li>
          )}
        </ul>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const stripe= new Stripe(process.env.STRIPE_SECRET_KEY, {
    apiVersion: "2020-08-27"
  });

  const prices = await stripe.prices.list({
    active: true,
    expand: ["data.product"],
  })

  return {props: {prices: prices.data } };
}