import Head from 'next/head'

import Footer from '../components/footer'
import ImageTopper from '../components/imagetopper'
import ProductSpecial from '../components/product/product speical'

export default function Home() {
  return (
    <>
      <Head>
        <title>eCanteen | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-100'>
        <ImageTopper 
        heading="Home"
        imagelarge="https://i.ibb.co/HxXSY0j/jason-wang-Nx-Awry-Abt-Iw-unsplash-1-1.png"
        imagesmall="https://i.ibb.co/B6qwqPT/jason-wang-Nx-Awry-Abt-Iw-unsplash-1.png"
        />
        
        <section>
            <ProductSpecial />
        </section>
        <Footer />
      </div>
      
    </>
  )
}
